DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(255),
    SURNAME    VARCHAR(255),
    MIDDLENAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE     VARCHAR(255),
    GENRE_ID  BIGINT,
    AUTHOR_ID BIGINT,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENT_AUTHOR VARCHAR(255),
    BOOK_ID        BIGINT,
    TEXT           VARCHAR,
    CREATED        TIMESTAMP,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);