DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), SURNAME VARCHAR(255), MIDDLENAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, TITLE VARCHAR(255), GENRE_ID BIGINT, AUTHOR_ID BIGINT);
